services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules  # Prevent overwriting node_modules
    command: ["yarn", "dev"]
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules  # Prevent overwriting node_modules
    command: bash -c "yarn prisma generate && yarn prisma migrate deploy && yarn start:dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sse_test
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
